"""empty message

Revision ID: 489d6b8cf7b7
Revises: d7c3a6bff0f6
Create Date: 2021-07-15 13:56:32.412506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489d6b8cf7b7'
down_revision = 'd7c3a6bff0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=256), nullable=False))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
